### ISSUE TITLE
Tests fail due to non-existing files

### ISSUE THREAD

**Issue by khanh-nguyen** [thompsy/jLTE-Simulator#1]
Thanks for a great work, Andrew. 
I'm having some issue running your code. Hope you can help. Currently, `mvn test` fails 24 tests out of 48. All the errors similar to the following:

```
longIntegTest(uk.co.downthewire.jLTE.integ.longer.AdaptiveSFRTest): Error reading fading data from
/path/to/fading-data/fading-iteration_0-channels_6555001-seed_11111.11111-speed_3.0kmh.bin - 
java.io.FileNotFoundException: 
/path/to/fading-data/fading-iteration_0-channels_6555001-seed_11111.11111-speed_3.0kmh.bin 
(No such file or directory)
```

I don't see in the code where you create these files. Maybe I was missing something. Do you mind giving me some instruction to resolve them?
Thanks,

**Comment by thompsy** [comment]
Hi, it looks like you closed the issue, but just so that this is clearer to others: in order to generate the fading data you need to run the GenerateFading class in the uk.co.downthewire.jLTE.fading package. This will generate the fading files required to run the simulator and write them out to the directory you specify.

Thanks

**Comment by khanh-nguyen** [comment]
Thanks for your quick response, Andrew. I should have read the README more carefully. I found it right after posting the issue. Sorry, my bad.
The only issue I have now is that you hardcoded some parameters like `numUEs, numSector, numRB`. Then these parameters are used to calculate `numFadingChannels`, which in turn is used in the name of files. This makes it very inconvenient to change the settings.
I'm still reading through your code to understand it.  But overall it's a great work and much more useful than the existing matlab lte simulator. Thank you very much for sharing your work.

**Comment by thompsy** [comment]
Yea, there are certainly a few places that aren't as straight-forward to modify as they could be. And, as you mention, the dependency between the numFadingChannels in GenerateFading and the filenames that are consumed is not as explicit as it could be.

While I'm not actively working with the simulator any more I'm more than happy to merge in pull requests that you think would make things easier for yourself and others to make use of it.

Thanks

**Comment by khanh-nguyen** [comment]
Thanks, Andrew. I'll try to make some commits once I understand your code better.
